backend:
  name: github
  repo: megankeesee/personal-site
  branch: master

media_folder: "assets/images"

collections:
- name: "articles" # Used in routes, ie.: /admin/collections/:slug/edit
  label: "Article" # Used in the UI, ie.: "New Article"
  files:
    - name: "Homepage"
      label: "Articles"
      file:  "data/articles.json"
      description: "List of articles that appear on the homepage"
      fields:
          - {label: "Latest Writings", name: "latest_writing", widget: "string"}
          - label: "Latest Writings"
            name: writings
            widget: "object"
            fields:
              - {label: "Publisher", name: "publisher", widget: "string"}
              - {label: "Date Posted", name: "date", widget: "datetime"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "url", name: "url", widget: "string"}